# Site Settings
title: Ramanpreet Singh

contacts:
  - name: Github
    link: https://github.com/singh-ramanpreet
    icon-class: icon brands fa-github
  - name: LinkedIn
    link: https://www.linkedin.com/in/singh-ramanpreet
    icon-class: icon brands fa-linkedin-in

markdown: kramdown

kramdown:
  auto_ids: false
  gfm_quirks: [paragraph_end]

exclude:
  - README.md

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

collections:
  pages:
    output: true
    permalink: /:name:output_ext
  posts:
    output: true
    permalink: /:name:output_ext
  drafts:
    output: true
    permalink: /:name:output_ext