baseURL: "/"
languageCode: "en-us"
title: "Ramanpreet Singh"
theme: "congo"

params:
  colorScheme: "ocean"
  enableCodeCopy: true
  enableImageLazyLoading: true
  enableImageWebp: true
  
  header:
    layout: "hybrid"
  
  homepage:
    layout: "profile"
  
  author:
    name: "Ramanpreet Singh, Ph.D."
    image: "img/avatar.png"
    headline: "Physicist, Data Scientist, Robotics, Automation and Software Developer"
    bio: "Always learning!"
    links:
      - linkedin: https://www.linkedin.com/in/singh-ramanpreet/
      - github: https://github.com/singh-ramanpreet

  list:
    groupByYear: false

  footer:
    showAppearanceSwitcher: true

menus:
  main:
    - name: "Projects"
      pageRef: "projects"
      weight: 10

    - name: "Education"
      url: "/page/about#education"
      weight: 20

    - name: "Experience"
      url: "/page/about#experience"
      weight: 30

    - name: "Publications"
      url: "/page/about#publications"
      weight: 40
